
package server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICT2WebService", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICT2WebService {


    /**
     * 
     * @param s1
     * @param s2
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLongestStringBetweenWithException", targetNamespace = "http://server/", className = "server.GetLongestStringBetweenWithException")
    @ResponseWrapper(localName = "getLongestStringBetweenWithExceptionResponse", targetNamespace = "http://server/", className = "server.GetLongestStringBetweenWithExceptionResponse")
    @Action(input = "http://server/ICT2WebService/getLongestStringBetweenWithExceptionRequest", output = "http://server/ICT2WebService/getLongestStringBetweenWithExceptionResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://server/ICT2WebService/getLongestStringBetweenWithException/Fault/Exception")
    })
    public String getLongestStringBetweenWithException(
        @WebParam(name = "s1", targetNamespace = "")
        String s1,
        @WebParam(name = "s2", targetNamespace = "")
        String s2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param s
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addSampleOnServer", targetNamespace = "http://server/", className = "server.AddSampleOnServer")
    @ResponseWrapper(localName = "addSampleOnServerResponse", targetNamespace = "http://server/", className = "server.AddSampleOnServerResponse")
    @Action(input = "http://server/ICT2WebService/addSampleOnServerRequest", output = "http://server/ICT2WebService/addSampleOnServerResponse")
    public Boolean addSampleOnServer(
        @WebParam(name = "s", targetNamespace = "")
        String s);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLongestStringOnServer", targetNamespace = "http://server/", className = "server.GetLongestStringOnServer")
    @ResponseWrapper(localName = "getLongestStringOnServerResponse", targetNamespace = "http://server/", className = "server.GetLongestStringOnServerResponse")
    @Action(input = "http://server/ICT2WebService/getLongestStringOnServerRequest", output = "http://server/ICT2WebService/getLongestStringOnServerResponse")
    public String getLongestStringOnServer();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isConnected", targetNamespace = "http://server/", className = "server.IsConnected")
    @ResponseWrapper(localName = "isConnectedResponse", targetNamespace = "http://server/", className = "server.IsConnectedResponse")
    @Action(input = "http://server/ICT2WebService/isConnectedRequest", output = "http://server/ICT2WebService/isConnectedResponse")
    public String isConnected();

    /**
     * 
     * @param s1
     * @param s2
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLongestStringBetween", targetNamespace = "http://server/", className = "server.GetLongestStringBetween")
    @ResponseWrapper(localName = "getLongestStringBetweenResponse", targetNamespace = "http://server/", className = "server.GetLongestStringBetweenResponse")
    @Action(input = "http://server/ICT2WebService/getLongestStringBetweenRequest", output = "http://server/ICT2WebService/getLongestStringBetweenResponse")
    public String getLongestStringBetween(
        @WebParam(name = "s1", targetNamespace = "")
        String s1,
        @WebParam(name = "s2", targetNamespace = "")
        String s2);

}
